apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-selfsigned-issuer
  namespace: rabbitmq-poc
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-ca
  namespace: rabbitmq-poc
spec:
  isCA: true
  commonName: rabbitmq-ca
  secretName: rabbitmq-ca-secret
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: rabbitmq-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-ca-issuer
  namespace: rabbitmq-poc
spec:
  ca:
    secretName: rabbitmq-ca-secret
