apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-server-cert
  namespace: rabbitmq-poc
spec:
  secretName: rabbitmq-server-tls
  duration: 8760h
  renewBefore: 720h
  commonName: "*.rabbitmq-poc-cluster.rabbitmq-poc.svc.cluster.local"
  dnsNames:
    - "rabbitmq-poc-cluster.rabbitmq-poc.svc.cluster.local"
    - "*.rabbitmq-poc-cluster.rabbitmq-poc.svc.cluster.local"
    - "rabbitmq-poc-cluster.rabbitmq-poc.svc"
    - "*.rabbitmq-poc-cluster.rabbitmq-poc.svc"
  issuerRef:
    name: rabbitmq-ca-issuer
    kind: Issuer
  privateKey:
    algorithm: ECDSA
    size: 256
