apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-client-cert
  namespace: rabbitmq-poc
spec:
  secretName: rabbitmq-client-tls
  duration: 8760h
  renewBefore: 720h
  commonName: rabbitmq-client
  usages:
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: rabbitmq-ca-issuer
    kind: Issuer
  privateKey:
    algorithm: ECDSA
    size: 256
